---
- hosts: all
  gather_facts: False
  become: true
  become_user: root
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: localhost
  connection: local
  become: true
  become_user: root
  tasks:
  - name: find local ssh keys
    find: path='./' patterns='id_rsa.*'
    register: ssh_found
  - name: create ssh key
    command: ssh-keygen -t rsa -N '' -f id_rsa
    run_once: true
    delegate_to: localhost
    ignore_errors: yes
    when: ssh_found.matched == 0

- hosts: all
  become: true
  become_user: root
#  vars:
#   domain: opsits.com
  tasks:
  - name: create and update ssh for shared communications
    include: tasks/ssh.yml
  - name: ensure hosts file is correct
    include: tasks/hosts.yml
  - name: ensure resolve has search for domain
    include: tasks/resolve.yml
  - name: upload files
    copy: src={{item}} dest=/root/{{item}} mode=0755
    with_items:
      - add_flavor.sh
      - debian.sh
      - debian-mn.sh
      - post-install.sh
      - debian-cmp.sh
      - setup_network.sh
      - multinode.sh
      - import_image.sh
      - node_delete.sh
      - launch.sh
  - name: upload multinode template
    copy: src=multinode.tmpl dest=/root/multinode

- hosts: control
  become: true
  become_user: root
  tasks:
  - name: configure debian-mn environment
    command: /root/debian-mn.sh
    register: mutli_node
    ignore_errors: true

- hosts: compute
  become: true
  become_user: root
  tasks:
  - name: congiure debian-cmp environment
    command: /root/debian-cmp.sh
    register: compute
    ignore_errors: true

- hosts: control
  become: true
  become_user: root
  tasks:
  - name: launch openstack with kolla
    command: kolla-ansible -i /root/multinode deploy
    register: deploy_multinode
    ignore_errors: true
  - name: run post-install config
    command: /root/post-install.sh
    register: post_install
    ignore_errors: true
  - name: enable masquerade (NAT) on external interface
    include: tasks/masq.yml
