# - name: remove hosts from /etc/hosts file
#   lineinfile: dest=/etc/hosts regexp='.*{{inventory_hostname}}.*' state=absent
# - name: add host to /etc/hosts
#   lineinfile: dest=/etc/hosts line='{{ansible_default_ipv4.address}} {{inventory_hostname}}.{{domain}} {{inventory_hostname}}'
#   when: domain is defined
# - name: add host to /etc/hosts
#   lineinfile: dest=/etc/hosts line='{{ansible_default_ipv4.address}} {{inventory_hostname}}'
#   when: domain is undefined
- name: load /etc/hosts from template
  template: src=templates/hosts.j2 dest=/etc/hosts mode=0644
